// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: service_appointment.proto

package serviceappointment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_service_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_appointment_proto_rawDescGZIP(), []int{0}
}

type ServiceIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceIdRequest) Reset() {
	*x = ServiceIdRequest{}
	mi := &file_service_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceIdRequest) ProtoMessage() {}

func (x *ServiceIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceIdRequest.ProtoReflect.Descriptor instead.
func (*ServiceIdRequest) Descriptor() ([]byte, []int) {
	return file_service_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceIdRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type ServiceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents      int32                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_service_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_service_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceResponse) GetPriceCents() int32 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *ServiceResponse) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceResponse     `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_service_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_service_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *ListServicesResponse) GetServices() []*ServiceResponse {
	if x != nil {
		return x.Services
	}
	return nil
}

type CreateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MasterId      string                 `protobuf:"bytes,2,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_service_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_service_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAppointmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAppointmentRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *CreateAppointmentRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CreateAppointmentRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

type AppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentResponse) Reset() {
	*x = AppointmentResponse{}
	mi := &file_service_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentResponse) ProtoMessage() {}

func (x *AppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentResponse.ProtoReflect.Descriptor instead.
func (*AppointmentResponse) Descriptor() ([]byte, []int) {
	return file_service_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *AppointmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppointmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListAppointmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*AppointmentResponse `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppointmentsResponse) Reset() {
	*x = ListAppointmentsResponse{}
	mi := &file_service_appointment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsResponse) ProtoMessage() {}

func (x *ListAppointmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_appointment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppointmentsResponse.ProtoReflect.Descriptor instead.
func (*ListAppointmentsResponse) Descriptor() ([]byte, []int) {
	return file_service_appointment_proto_rawDescGZIP(), []int{6}
}

func (x *ListAppointmentsResponse) GetAppointments() []*AppointmentResponse {
	if x != nil {
		return x.Appointments
	}
	return nil
}

type AppointmentIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentIdRequest) Reset() {
	*x = AppointmentIdRequest{}
	mi := &file_service_appointment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentIdRequest) ProtoMessage() {}

func (x *AppointmentIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_appointment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentIdRequest.ProtoReflect.Descriptor instead.
func (*AppointmentIdRequest) Descriptor() ([]byte, []int) {
	return file_service_appointment_proto_rawDescGZIP(), []int{7}
}

func (x *AppointmentIdRequest) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

type UserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	mi := &file_service_appointment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_appointment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_service_appointment_proto_rawDescGZIP(), []int{8}
}

func (x *UserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_service_appointment_proto protoreflect.FileDescriptor

const file_service_appointment_proto_rawDesc = "" +
	"\n" +
	"\x19service_appointment.proto\x12\vappointment\"\a\n" +
	"\x05Empty\"1\n" +
	"\x10ServiceIdRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"\xa3\x01\n" +
	"\x0fServiceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x05R\n" +
	"priceCents\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\x05R\x0fdurationMinutes\"P\n" +
	"\x14ListServicesResponse\x128\n" +
	"\bservices\x18\x01 \x03(\v2\x1c.appointment.ServiceResponseR\bservices\"\x8e\x01\n" +
	"\x18CreateAppointmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmaster_id\x18\x02 \x01(\tR\bmasterId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\"=\n" +
	"\x13AppointmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"`\n" +
	"\x18ListAppointmentsResponse\x12D\n" +
	"\fappointments\x18\x01 \x03(\v2 .appointment.AppointmentResponseR\fappointments\"=\n" +
	"\x14AppointmentIdRequest\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\"(\n" +
	"\rUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2\xb6\x03\n" +
	"\x19ServiceAppointmentService\x12E\n" +
	"\fListServices\x12\x12.appointment.Empty\x1a!.appointment.ListServicesResponse\x12M\n" +
	"\x0eGetServiceById\x12\x1d.appointment.ServiceIdRequest\x1a\x1c.appointment.ServiceResponse\x12\\\n" +
	"\x11CreateAppointment\x12%.appointment.CreateAppointmentRequest\x1a .appointment.AppointmentResponse\x12Y\n" +
	"\x14ListUserAppointments\x12\x1a.appointment.UserIdRequest\x1a%.appointment.ListAppointmentsResponse\x12J\n" +
	"\x11CancelAppointment\x12!.appointment.AppointmentIdRequest\x1a\x12.appointment.EmptyB.Z,appointment-service/proto;serviceappointmentb\x06proto3"

var (
	file_service_appointment_proto_rawDescOnce sync.Once
	file_service_appointment_proto_rawDescData []byte
)

func file_service_appointment_proto_rawDescGZIP() []byte {
	file_service_appointment_proto_rawDescOnce.Do(func() {
		file_service_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_appointment_proto_rawDesc), len(file_service_appointment_proto_rawDesc)))
	})
	return file_service_appointment_proto_rawDescData
}

var file_service_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_appointment_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: appointment.Empty
	(*ServiceIdRequest)(nil),         // 1: appointment.ServiceIdRequest
	(*ServiceResponse)(nil),          // 2: appointment.ServiceResponse
	(*ListServicesResponse)(nil),     // 3: appointment.ListServicesResponse
	(*CreateAppointmentRequest)(nil), // 4: appointment.CreateAppointmentRequest
	(*AppointmentResponse)(nil),      // 5: appointment.AppointmentResponse
	(*ListAppointmentsResponse)(nil), // 6: appointment.ListAppointmentsResponse
	(*AppointmentIdRequest)(nil),     // 7: appointment.AppointmentIdRequest
	(*UserIdRequest)(nil),            // 8: appointment.UserIdRequest
}
var file_service_appointment_proto_depIdxs = []int32{
	2, // 0: appointment.ListServicesResponse.services:type_name -> appointment.ServiceResponse
	5, // 1: appointment.ListAppointmentsResponse.appointments:type_name -> appointment.AppointmentResponse
	0, // 2: appointment.ServiceAppointmentService.ListServices:input_type -> appointment.Empty
	1, // 3: appointment.ServiceAppointmentService.GetServiceById:input_type -> appointment.ServiceIdRequest
	4, // 4: appointment.ServiceAppointmentService.CreateAppointment:input_type -> appointment.CreateAppointmentRequest
	8, // 5: appointment.ServiceAppointmentService.ListUserAppointments:input_type -> appointment.UserIdRequest
	7, // 6: appointment.ServiceAppointmentService.CancelAppointment:input_type -> appointment.AppointmentIdRequest
	3, // 7: appointment.ServiceAppointmentService.ListServices:output_type -> appointment.ListServicesResponse
	2, // 8: appointment.ServiceAppointmentService.GetServiceById:output_type -> appointment.ServiceResponse
	5, // 9: appointment.ServiceAppointmentService.CreateAppointment:output_type -> appointment.AppointmentResponse
	6, // 10: appointment.ServiceAppointmentService.ListUserAppointments:output_type -> appointment.ListAppointmentsResponse
	0, // 11: appointment.ServiceAppointmentService.CancelAppointment:output_type -> appointment.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_appointment_proto_init() }
func file_service_appointment_proto_init() {
	if File_service_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_appointment_proto_rawDesc), len(file_service_appointment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_appointment_proto_goTypes,
		DependencyIndexes: file_service_appointment_proto_depIdxs,
		MessageInfos:      file_service_appointment_proto_msgTypes,
	}.Build()
	File_service_appointment_proto = out.File
	file_service_appointment_proto_goTypes = nil
	file_service_appointment_proto_depIdxs = nil
}
