// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rating_notification.proto

package rating_notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      string                 `protobuf:"bytes,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRatingRequest) Reset() {
	*x = CreateRatingRequest{}
	mi := &file_rating_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRatingRequest) ProtoMessage() {}

func (x *CreateRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRatingRequest.ProtoReflect.Descriptor instead.
func (*CreateRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_notification_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRatingRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *CreateRatingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRatingRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CreateRatingRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MasterId      string                 `protobuf:"bytes,2,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingResponse) Reset() {
	*x = RatingResponse{}
	mi := &file_rating_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingResponse) ProtoMessage() {}

func (x *RatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingResponse.ProtoReflect.Descriptor instead.
func (*RatingResponse) Descriptor() ([]byte, []int) {
	return file_rating_notification_proto_rawDescGZIP(), []int{1}
}

func (x *RatingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RatingResponse) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *RatingResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RatingResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RatingResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RatingResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MasterIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      string                 `protobuf:"bytes,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterIdRequest) Reset() {
	*x = MasterIdRequest{}
	mi := &file_rating_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterIdRequest) ProtoMessage() {}

func (x *MasterIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterIdRequest.ProtoReflect.Descriptor instead.
func (*MasterIdRequest) Descriptor() ([]byte, []int) {
	return file_rating_notification_proto_rawDescGZIP(), []int{2}
}

func (x *MasterIdRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

type ListRatingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ratings       []*RatingResponse      `protobuf:"bytes,1,rep,name=ratings,proto3" json:"ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRatingsResponse) Reset() {
	*x = ListRatingsResponse{}
	mi := &file_rating_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRatingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRatingsResponse) ProtoMessage() {}

func (x *ListRatingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRatingsResponse.ProtoReflect.Descriptor instead.
func (*ListRatingsResponse) Descriptor() ([]byte, []int) {
	return file_rating_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ListRatingsResponse) GetRatings() []*RatingResponse {
	if x != nil {
		return x.Ratings
	}
	return nil
}

type DeleteRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRatingRequest) Reset() {
	*x = DeleteRatingRequest{}
	mi := &file_rating_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRatingRequest) ProtoMessage() {}

func (x *DeleteRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRatingRequest.ProtoReflect.Descriptor instead.
func (*DeleteRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_notification_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRatingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rating_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rating_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rating_notification_proto_rawDescGZIP(), []int{5}
}

var File_rating_notification_proto protoreflect.FileDescriptor

const file_rating_notification_proto_rawDesc = "" +
	"\n" +
	"\x19rating_notification.proto\x12\x06rating\"{\n" +
	"\x13CreateRatingRequest\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\tR\bmasterId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"\xa5\x01\n" +
	"\x0eRatingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmaster_id\x18\x02 \x01(\tR\bmasterId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\".\n" +
	"\x0fMasterIdRequest\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\tR\bmasterId\"G\n" +
	"\x13ListRatingsResponse\x120\n" +
	"\aratings\x18\x01 \x03(\v2\x16.rating.RatingResponseR\aratings\"%\n" +
	"\x13DeleteRatingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty2\xdb\x01\n" +
	"\rRatingService\x12C\n" +
	"\fCreateRating\x12\x1b.rating.CreateRatingRequest\x1a\x16.rating.RatingResponse\x12I\n" +
	"\x11ListMasterRatings\x12\x17.rating.MasterIdRequest\x1a\x1b.rating.ListRatingsResponse\x12:\n" +
	"\fDeleteRating\x12\x1b.rating.DeleteRatingRequest\x1a\r.rating.EmptyB7Z5rating-notification-service/proto;rating_notificationb\x06proto3"

var (
	file_rating_notification_proto_rawDescOnce sync.Once
	file_rating_notification_proto_rawDescData []byte
)

func file_rating_notification_proto_rawDescGZIP() []byte {
	file_rating_notification_proto_rawDescOnce.Do(func() {
		file_rating_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rating_notification_proto_rawDesc), len(file_rating_notification_proto_rawDesc)))
	})
	return file_rating_notification_proto_rawDescData
}

var file_rating_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rating_notification_proto_goTypes = []any{
	(*CreateRatingRequest)(nil), // 0: rating.CreateRatingRequest
	(*RatingResponse)(nil),      // 1: rating.RatingResponse
	(*MasterIdRequest)(nil),     // 2: rating.MasterIdRequest
	(*ListRatingsResponse)(nil), // 3: rating.ListRatingsResponse
	(*DeleteRatingRequest)(nil), // 4: rating.DeleteRatingRequest
	(*Empty)(nil),               // 5: rating.Empty
}
var file_rating_notification_proto_depIdxs = []int32{
	1, // 0: rating.ListRatingsResponse.ratings:type_name -> rating.RatingResponse
	0, // 1: rating.RatingService.CreateRating:input_type -> rating.CreateRatingRequest
	2, // 2: rating.RatingService.ListMasterRatings:input_type -> rating.MasterIdRequest
	4, // 3: rating.RatingService.DeleteRating:input_type -> rating.DeleteRatingRequest
	1, // 4: rating.RatingService.CreateRating:output_type -> rating.RatingResponse
	3, // 5: rating.RatingService.ListMasterRatings:output_type -> rating.ListRatingsResponse
	5, // 6: rating.RatingService.DeleteRating:output_type -> rating.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rating_notification_proto_init() }
func file_rating_notification_proto_init() {
	if File_rating_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rating_notification_proto_rawDesc), len(file_rating_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rating_notification_proto_goTypes,
		DependencyIndexes: file_rating_notification_proto_depIdxs,
		MessageInfos:      file_rating_notification_proto_msgTypes,
	}.Build()
	File_rating_notification_proto = out.File
	file_rating_notification_proto_goTypes = nil
	file_rating_notification_proto_depIdxs = nil
}
