// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: user_master.proto

package usermaster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	mi := &file_user_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{2}
}

func (x *UserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MasterIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      string                 `protobuf:"bytes,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterIdRequest) Reset() {
	*x = MasterIdRequest{}
	mi := &file_user_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterIdRequest) ProtoMessage() {}

func (x *MasterIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterIdRequest.ProtoReflect.Descriptor instead.
func (*MasterIdRequest) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{3}
}

func (x *MasterIdRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

type CreateMasterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Experience    int32                  `protobuf:"varint,3,opt,name=experience,proto3" json:"experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMasterRequest) Reset() {
	*x = CreateMasterRequest{}
	mi := &file_user_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterRequest) ProtoMessage() {}

func (x *CreateMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterRequest.ProtoReflect.Descriptor instead.
func (*CreateMasterRequest) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMasterRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMasterRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreateMasterRequest) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

type UpdateMasterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      string                 `protobuf:"bytes,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	Experience    int32                  `protobuf:"varint,3,opt,name=experience,proto3" json:"experience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMasterRequest) Reset() {
	*x = UpdateMasterRequest{}
	mi := &file_user_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMasterRequest) ProtoMessage() {}

func (x *UpdateMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMasterRequest.ProtoReflect.Descriptor instead.
func (*UpdateMasterRequest) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMasterRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *UpdateMasterRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateMasterRequest) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_user_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{6}
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{7}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type MasterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Rating        float64                `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterResponse) Reset() {
	*x = MasterResponse{}
	mi := &file_user_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterResponse) ProtoMessage() {}

func (x *MasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterResponse.ProtoReflect.Descriptor instead.
func (*MasterResponse) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{8}
}

func (x *MasterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MasterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MasterResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *MasterResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type ListMastersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Masters       []*MasterResponse      `protobuf:"bytes,1,rep,name=masters,proto3" json:"masters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMastersResponse) Reset() {
	*x = ListMastersResponse{}
	mi := &file_user_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMastersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMastersResponse) ProtoMessage() {}

func (x *ListMastersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMastersResponse.ProtoReflect.Descriptor instead.
func (*ListMastersResponse) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{9}
}

func (x *ListMastersResponse) GetMasters() []*MasterResponse {
	if x != nil {
		return x.Masters
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *UserResponse          `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_master_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_master_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_master_proto_rawDescGZIP(), []int{10}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUser() *UserResponse {
	if x != nil {
		return x.User
	}
	return nil
}

var File_user_master_proto protoreflect.FileDescriptor

const file_user_master_proto_rawDesc = "" +
	"\n" +
	"\x11user_master.proto\x12\n" +
	"usermaster\"W\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"(\n" +
	"\rUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\x0fMasterIdRequest\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\tR\bmasterId\"`\n" +
	"\x13CreateMasterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x1e\n" +
	"\n" +
	"experience\x18\x03 \x01(\x05R\n" +
	"experience\"d\n" +
	"\x13UpdateMasterRequest\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\tR\bmasterId\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x1e\n" +
	"\n" +
	"experience\x18\x03 \x01(\x05R\n" +
	"experience\"\a\n" +
	"\x05Empty\"\\\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"^\n" +
	"\x0eMasterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x01R\x06rating\"K\n" +
	"\x13ListMastersResponse\x124\n" +
	"\amasters\x18\x01 \x03(\v2\x1a.usermaster.MasterResponseR\amasters\"S\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12,\n" +
	"\x04user\x18\x02 \x01(\v2\x18.usermaster.UserResponseR\x04user2\x8a\x04\n" +
	"\x11UserMasterService\x12E\n" +
	"\fRegisterUser\x12\x1b.usermaster.RegisterRequest\x1a\x18.usermaster.UserResponse\x12@\n" +
	"\tLoginUser\x12\x18.usermaster.LoginRequest\x1a\x19.usermaster.LoginResponse\x12E\n" +
	"\x0eGetUserProfile\x12\x19.usermaster.UserIdRequest\x1a\x18.usermaster.UserResponse\x12A\n" +
	"\vListMasters\x12\x11.usermaster.Empty\x1a\x1f.usermaster.ListMastersResponse\x12H\n" +
	"\rGetMasterByID\x12\x1b.usermaster.MasterIdRequest\x1a\x1a.usermaster.MasterResponse\x12K\n" +
	"\fCreateMaster\x12\x1f.usermaster.CreateMasterRequest\x1a\x1a.usermaster.MasterResponse\x12K\n" +
	"\fUpdateMaster\x12\x1f.usermaster.UpdateMasterRequest\x1a\x1a.usermaster.MasterResponseB&Z$user-master-service/proto;usermasterb\x06proto3"

var (
	file_user_master_proto_rawDescOnce sync.Once
	file_user_master_proto_rawDescData []byte
)

func file_user_master_proto_rawDescGZIP() []byte {
	file_user_master_proto_rawDescOnce.Do(func() {
		file_user_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_master_proto_rawDesc), len(file_user_master_proto_rawDesc)))
	})
	return file_user_master_proto_rawDescData
}

var file_user_master_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_master_proto_goTypes = []any{
	(*RegisterRequest)(nil),     // 0: usermaster.RegisterRequest
	(*LoginRequest)(nil),        // 1: usermaster.LoginRequest
	(*UserIdRequest)(nil),       // 2: usermaster.UserIdRequest
	(*MasterIdRequest)(nil),     // 3: usermaster.MasterIdRequest
	(*CreateMasterRequest)(nil), // 4: usermaster.CreateMasterRequest
	(*UpdateMasterRequest)(nil), // 5: usermaster.UpdateMasterRequest
	(*Empty)(nil),               // 6: usermaster.Empty
	(*UserResponse)(nil),        // 7: usermaster.UserResponse
	(*MasterResponse)(nil),      // 8: usermaster.MasterResponse
	(*ListMastersResponse)(nil), // 9: usermaster.ListMastersResponse
	(*LoginResponse)(nil),       // 10: usermaster.LoginResponse
}
var file_user_master_proto_depIdxs = []int32{
	8,  // 0: usermaster.ListMastersResponse.masters:type_name -> usermaster.MasterResponse
	7,  // 1: usermaster.LoginResponse.user:type_name -> usermaster.UserResponse
	0,  // 2: usermaster.UserMasterService.RegisterUser:input_type -> usermaster.RegisterRequest
	1,  // 3: usermaster.UserMasterService.LoginUser:input_type -> usermaster.LoginRequest
	2,  // 4: usermaster.UserMasterService.GetUserProfile:input_type -> usermaster.UserIdRequest
	6,  // 5: usermaster.UserMasterService.ListMasters:input_type -> usermaster.Empty
	3,  // 6: usermaster.UserMasterService.GetMasterByID:input_type -> usermaster.MasterIdRequest
	4,  // 7: usermaster.UserMasterService.CreateMaster:input_type -> usermaster.CreateMasterRequest
	5,  // 8: usermaster.UserMasterService.UpdateMaster:input_type -> usermaster.UpdateMasterRequest
	7,  // 9: usermaster.UserMasterService.RegisterUser:output_type -> usermaster.UserResponse
	10, // 10: usermaster.UserMasterService.LoginUser:output_type -> usermaster.LoginResponse
	7,  // 11: usermaster.UserMasterService.GetUserProfile:output_type -> usermaster.UserResponse
	9,  // 12: usermaster.UserMasterService.ListMasters:output_type -> usermaster.ListMastersResponse
	8,  // 13: usermaster.UserMasterService.GetMasterByID:output_type -> usermaster.MasterResponse
	8,  // 14: usermaster.UserMasterService.CreateMaster:output_type -> usermaster.MasterResponse
	8,  // 15: usermaster.UserMasterService.UpdateMaster:output_type -> usermaster.MasterResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_user_master_proto_init() }
func file_user_master_proto_init() {
	if File_user_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_master_proto_rawDesc), len(file_user_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_master_proto_goTypes,
		DependencyIndexes: file_user_master_proto_depIdxs,
		MessageInfos:      file_user_master_proto_msgTypes,
	}.Build()
	File_user_master_proto = out.File
	file_user_master_proto_goTypes = nil
	file_user_master_proto_depIdxs = nil
}
